# Generated by Django 5.2.5 on 2025-08-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_vendorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service_category',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1 years'), ('2-5', '2-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='service_category',
            field=models.CharField(choices=[('decoration', 'Event Decoration'), ('catering', 'Catering Services'), ('photography', 'Photography & Videography'), ('venue', 'Venue Management'), ('entertainment', 'Entertainment'), ('planning', 'Event Planning'), ('lighting', 'Lighting & Audio'), ('transport', 'Transportation'), ('other', 'Other Services')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event.user'),
        ),
    ]
