# Generated by Django 5.2.5 on 2025-08-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_user_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='experience',
            field=models.CharField(choices=[('1', '1 years'), ('2', '2 years'), ('6', '6 years'), ('10+', '10+ years')], max_length=10),
        ),
        migrations.CreateModel(
            name='VendorDis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_images/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('decoration', 'Event Decoration'), ('catering', 'Catering Services'), ('photography', 'Photography & Videography'), ('venue', 'Venue Management'), ('entertainment', 'Entertainment'), ('planning', 'Event Planning'), ('lighting', 'Lighting & Audio'), ('transport', 'Transportation'), ('other', 'Other Services')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.vendorprofile')),
            ],
        ),
    ]
