# Generated by Django 5.2.5 on 2025-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_vendorprofile_experience_vendordis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordis',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
