# Generated by Django 5.2.5 on 2025-08-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_vendordis_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordis',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
