# Generated by Django 5.2.5 on 2025-08-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_vendordis_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordis',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
